config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  root "home#index"
  
  get '/balance', to: "balance#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/commands/balance.rb
class Commands::Balance
  def initialize(user:)
    @user = user
  end
  
  def execute
    Operation.where(user:).sum(Money.zero, &:amount) 
  end

  private
  
  attr_reader :user
end

app/models/commands/transfer.rb
class Commands::Transfer
  
  def execute(from:, to:, amount:)
    ActiveRecord::Base.transaction do
      Operation.create!(user: from, amount: amount * -1, description: "transfer to #{to.email}", operation_type: 'transfer_out')
      Operation.create!(user: to, amount:, description: "transfer from #{to.email}", operation_type: 'transfer_in')
    end
  end
  
end

app/models/commands/welcome.rb
class Commands::Welcome
  def initialize(user:)
    @user = user
  end
  
  def execute
    Operation.create!(user:, amount: AMOUNT, description: 'welcome bonus', operation_type: 'welcome')
  end
  
  private
  
  attr_reader :user
  
  AMOUNT = Money.from_amount(100, 'BAM')
  private_constant :AMOUNT
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :user
  
  monetize :amount_cents
  
  validates :operation_type, presence: true, inclusion: { in: %w[welcome transfer_in transfer_out] }
  validates :description, presence: true
  
  validates :amount, presence: true
  validate :amount_positive
  validate :bam_currency
  
  private
  
  def amount_positive
    errors.add(:amount, "can't be zero") if amount.to_i.zero?
  end
  
  def bam_currency
    errors.add(:amount, "only support operation in BAM") unless amount.currency.iso_code == 'BAM'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :operations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/balance_controller.rb
class BalanceController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @balance = Commands::Balance.new(user: current_user).execute
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  
  # POST /resource
  def create
    super do |user|
      Commands::Welcome.new(user:).execute
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/balance/show.html.erb
<h1>Your balance is <%= @balance.format %></h1>

app/views/home/index.html.erb
<h1 class="text-3xl font-bold underline">
    Welcome to Bambank
</h1>

<%= link_to 'Your balance', balance_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bambank</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <div class="bg-white">
        <header class="absolute inset-x-0 top-0 z-50">
          <nav class="flex items-center justify-between p-6 lg:px-8" aria-label="Global">
            <div class="flex lg:flex-1">
              <a href="#" class="-m-1.5 p-1.5">
                <span class="sr-only">Your Company</span>
                <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600" alt="">
              </a>
            </div>
            <div class="flex lg:hidden">
              <button type="button" class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
                <span class="sr-only">Open main menu</span>
                <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
                </svg>
              </button>
            </div>
            <div class="hidden lg:flex lg:flex-1 lg:justify-end">
              <% if user_signed_in? %>
                <%= current_user.email %>
                <%= link_to "Sign Out", destroy_user_session_path, data: { "turbo-method": :delete } %>
              <% else %>
                <%= link_to "Sign up", new_user_registration_path, class: "text-sm font-semibold leading-6 text-gray-900" %>
                &nbsp;
                <%= link_to "Log in", new_user_session_path, class: "text-sm font-semibold leading-6 text-gray-900" %>
              <% end %>
            </div>
          </nav>
        </header>
      
        <div class="relative isolate px-6 pt-14 lg:px-8">
         <%= yield %>
        </div>
      </div>
    </main>
  </body>
</html>